/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coliridnho;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author 20241SG.INF_I0053
 */
public class Coloridinho extends javax.swing.JFrame {

    /**
     * Creates new form Coloridinho
     */
    public Coloridinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fonteBrancaButton = new javax.swing.JButton();
        fontePretaButton = new javax.swing.JButton();
        fundoBrancoButton = new javax.swing.JButton();
        fundoPretoButton = new javax.swing.JButton();
        fundoRosaButton = new javax.swing.JButton();
        fundoRoxoButton = new javax.swing.JButton();
        fundoAzulButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        estiloNormal = new javax.swing.JButton();
        estiloNegrito = new javax.swing.JButton();
        estiloItalico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cor do texto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cor do fundo");

        fonteBrancaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fonteBrancaButton.setText("Branco");
        fonteBrancaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonteBrancaButtonActionPerformed(evt);
            }
        });

        fontePretaButton.setBackground(new java.awt.Color(0, 0, 0));
        fontePretaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fontePretaButton.setForeground(new java.awt.Color(255, 255, 255));
        fontePretaButton.setText("Preto");
        fontePretaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontePretaButtonActionPerformed(evt);
            }
        });

        fundoBrancoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fundoBrancoButton.setText("Branco");
        fundoBrancoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundoBrancoButtonActionPerformed(evt);
            }
        });

        fundoPretoButton.setBackground(new java.awt.Color(0, 0, 0));
        fundoPretoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fundoPretoButton.setForeground(new java.awt.Color(255, 255, 255));
        fundoPretoButton.setText("Preto");
        fundoPretoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundoPretoButtonActionPerformed(evt);
            }
        });

        fundoRosaButton.setBackground(new java.awt.Color(255, 51, 255));
        fundoRosaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fundoRosaButton.setForeground(new java.awt.Color(255, 255, 255));
        fundoRosaButton.setText("Rosa");
        fundoRosaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundoRosaButtonActionPerformed(evt);
            }
        });

        fundoRoxoButton.setBackground(new java.awt.Color(102, 0, 153));
        fundoRoxoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fundoRoxoButton.setForeground(new java.awt.Color(255, 255, 255));
        fundoRoxoButton.setText("Roxo");
        fundoRoxoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundoRoxoButtonActionPerformed(evt);
            }
        });

        fundoAzulButton.setBackground(new java.awt.Color(0, 0, 255));
        fundoAzulButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fundoAzulButton.setForeground(new java.awt.Color(255, 255, 255));
        fundoAzulButton.setText("Azul");
        fundoAzulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundoAzulButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Estilo do texto");

        estiloNormal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estiloNormal.setText("Normal");
        estiloNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloNormalActionPerformed(evt);
            }
        });

        estiloNegrito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        estiloNegrito.setText("Negrito");
        estiloNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloNegritoActionPerformed(evt);
            }
        });

        estiloItalico.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        estiloItalico.setText("Itálico");
        estiloItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloItalicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fontePretaButton)
                            .addComponent(fonteBrancaButton))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fundoBrancoButton)
                            .addComponent(fundoPretoButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fundoRosaButton)
                            .addComponent(fundoRoxoButton)
                            .addComponent(fundoAzulButton))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estiloItalico)
                            .addComponent(estiloNegrito)
                            .addComponent(estiloNormal))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fonteBrancaButton)
                            .addComponent(fundoBrancoButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fontePretaButton)
                            .addComponent(fundoPretoButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fundoRosaButton)
                        .addGap(18, 18, 18)
                        .addComponent(fundoRoxoButton)
                        .addGap(18, 18, 18)
                        .addComponent(fundoAzulButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estiloNormal)
                        .addGap(18, 18, 18)
                        .addComponent(estiloNegrito)
                        .addGap(18, 18, 18)
                        .addComponent(estiloItalico)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fontePretaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontePretaButtonActionPerformed
        // TODO add your handling code here:
        textArea.setForeground(Color.BLACK);
    }//GEN-LAST:event_fontePretaButtonActionPerformed

    private void fundoPretoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundoPretoButtonActionPerformed
        // TODO add your handling code here:
        textArea.setBackground(Color.BLACK);
    }//GEN-LAST:event_fundoPretoButtonActionPerformed

    private void fundoRosaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundoRosaButtonActionPerformed
        // TODO add your handling code here:
        textArea.setBackground(Color.magenta);
    }//GEN-LAST:event_fundoRosaButtonActionPerformed

    private void fundoRoxoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundoRoxoButtonActionPerformed
        // TODO add your handling code here:
        textArea.setBackground(Color.decode("#800080"));
    }//GEN-LAST:event_fundoRoxoButtonActionPerformed

    private void fundoAzulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundoAzulButtonActionPerformed
        // TODO add your handling code here:
        textArea.setBackground(Color.BLUE);
    }//GEN-LAST:event_fundoAzulButtonActionPerformed

    private void fonteBrancaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonteBrancaButtonActionPerformed
        // TODO add your handling code here:
        textArea.setForeground(Color.WHITE);
    }//GEN-LAST:event_fonteBrancaButtonActionPerformed

    private void fundoBrancoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundoBrancoButtonActionPerformed
        // TODO add your handling code here:
        textArea.setBackground(Color.WHITE);
    }//GEN-LAST:event_fundoBrancoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    Font normal = new Font("Arial", Font.PLAIN, 12);
    Font italica = new Font("Arial", Font.ITALIC, 12);
    Font negrita = new Font("Arial", Font.BOLD, 12);

    private void estiloNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloNormalActionPerformed
        // TODO add your handling code here:
        textArea.setFont(normal);
    }//GEN-LAST:event_estiloNormalActionPerformed

    private void estiloNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloNegritoActionPerformed
        // TODO add your handling code here:
        textArea.setFont(negrita);
    }//GEN-LAST:event_estiloNegritoActionPerformed

    private void estiloItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloItalicoActionPerformed
        // TODO add your handling code here:
        textArea.setFont(italica);  
    }//GEN-LAST:event_estiloItalicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coloridinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coloridinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coloridinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coloridinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coloridinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estiloItalico;
    private javax.swing.JButton estiloNegrito;
    private javax.swing.JButton estiloNormal;
    private javax.swing.JButton fonteBrancaButton;
    private javax.swing.JButton fontePretaButton;
    private javax.swing.JButton fundoAzulButton;
    private javax.swing.JButton fundoBrancoButton;
    private javax.swing.JButton fundoPretoButton;
    private javax.swing.JButton fundoRosaButton;
    private javax.swing.JButton fundoRoxoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
